
### Category add
POST localhost:8080/category
Content-Type: application/json

{
  "name": "Quruq mevalarwe"
}

### Category update
PUT localhost:8080/category
Content-Type: application/json

{
  "id": 1,
  "name": "Mevalar"
}

### Category get id
GET localhost:8080/category/1


### Category get all
GET localhost:8080/category