
### Product add
POST localhost:8080/product
Content-Type: application/json

{
  "name": "Olma",
  "price": 10000,
  "categoryId": 1
}

### Product update
PUT localhost:8080/product
Content-Type: application/json

{
  "id": 1,
  "name": "Qizil olma",
  "price": 5000,
  "categoryId": 2
}

### Product get id
GET localhost:8080/product/1

###  get all Product category id
GET http://localhost:8080/product/category-id/1


### Product get all
GET localhost:8080/category